# Generated by Django 4.0.5 on 2022-07-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DelivveryOptions',
            new_name='DeliveryOptions',
        ),
    ]
